#!/bin/sh
# bkfile: This script makes backup file
#         with the name originalname.CCYYMMDD.
# usage: bkfile originalfile

TODAY=`date +%Y%m%d`

# (Optional) Directory to save backup files.
BKDIR=""

if [ $# -ne 1 ];
then
  echo "usage: bkfile filename"
  exit 9
fi

if [ ! -e $1 ]
then
  echo "$1 does not exist!"
  exit 9
fi

if [ $BKDIR ] 
then 
  if [ ! -d $BKDIR ] 
  then 
    echo "unknown BKDIR: $BKDIR not found"
    exit 9
  else
    TARGET=${BKDIR}/$1 
  fi
else
  TARGET=$1
fi

if [ ! -e ${TARGET}.${TODAY} ]
then
  BKFILE=${TARGET}.${TODAY}
else
  icount=1
  while :
  do
    if [ ! -e ${TARGET}.${TODAY}_$icount ]
    then
      BKFILE=${TARGET}.${TODAY}_$icount
      break
    else
      icount=`echo "$icount +1" | bc -l`
    fi
  done
fi

cp -p $1 $BKFILE

exit
